### PR TITLE
Safe writes

### PR DESCRIPTION
**Pull request by markunsworth**
The `MongoClient` and `MongoReplicasetClient` are being initialised with `safe=False` which means writes are not safe.

### CODE REVIEW

**Comment by aburgel** [comment]
Do you have any thoughts on why this decision was made? I'm happy to merge this in but it seems like this was a deliberate decision and I'd like to understand it first.

**Comment by markunsworth** [comment]
It was added in commit https://github.com/django-nonrel/mongodb-engine/commit/96402128d3732f6c60d05b5b1871ae6eafa94880 by @r4fek.

The MongoClient (and MongoReplicaSetClient) were actually introduced to make the behaviour of safe writes default. Previously the Connection and ReplicasetConnection would use the fire and forget behaviour for which MongoDB has come under a lot of criticism and they were deprecated in pymongo 2.4. 

We could make the behaviour optional using a writeconcern configuration option (safe has also been deprecated), but just allowing writes to fail silently by default is a bit broken.

**Comment by aburgel** [comment]
I'm fine with merging this in, but it looks like the tests are failing. Can you take a look at that?

**Comment by markunsworth** [comment]
Looks like these are caused by the changes in the latest version of pymongo. The master build hasn't been built for 10 months and would likely fail right now aswell

Pymongo 3 has introduced a number of breaking changes. In this case they have changed the keyword argument from `fields` to `projections` on the find/find_one methods

I can fix the version of pymongo used to be < 3.0 for now, but changing this for pymongo 3 would require a number of changes which I think are outside of this

**Comment by markunsworth** [comment]
So having checked out the upstream master (https://github.com/django-nonrel/mongodb-engine) and run the tests it seems these arent related to this pull request.

There's a whole heap of issues around the changes in pymongo 3.0, a lack of teardown in between tests meaning stale data, fixture teardown against capped collections failing etc etc

**Comment by markunsworth** [comment]
This fixes #152

**Pull request merged**
